logger: {
  logfile: stdout,
  level: debug,
}

api: {
  baseURL: /api,
  settingsURL: /settings,
  profileURL: /profile,
  sessionsUrl: /sessions,
  teamsURL: /teams,
  tournamentsURL: /tournaments,
  meetingsURL: /meetings,
  attachURL: /attachments,
}

server: {
  address: 0.0.0.0:8080,
}

cors: {
  allowed_origins: [
      https://sport4all.tech,
      http://localhost:8001,
  ]
}

psql: {
  dbms: postgres,
  host: postgres,
  user: sport4all_user,
  password: sport4all,
  name: sport4all_db,
  sslmode: disable,
}

redis: {
  address: redis:6379,
  protocol: tcp,
  expiresKeySec: 31536000, # 1 year
}

s3: {
  bucket: sport4all,
  region: us-east-2,
}
