logger: {
  logfile: stdout,
  level: debug,
}

api: {
  baseURL: /api,
  settingsURL: /settings,
  profileURL: /profile,
  sessionsUrl: /sessions,
  teamsURL: /teams,
  sportsURL: /sports,
  tournamentsURL: /tournaments,
  meetingsURL: /meetings,
  skillsURL: /skills,
  attachURL: /attachments,
  messageURL: /messages,
  inviteURL: /invites
}

server: {
  address: localhost:8080,
}

cors: {
  allowed_origins: [
      http://localhost:8001,
      http://localhost:8080,
  ]
}

ocr: {
  address: localhost:8090,
}

psql: {
  dbms: postgres,
  host: localhost,
  user: sport4all_user,
  password: sport4all,
  name: sport4all_db,
  sslmode: disable,
}

redis: {
  address: localhost:6379,
  protocol: tcp,
  expiresKeySec: 31536000, # 1 year
}

rabbitmq: {
  address: localhost:5672,
  user: sport4all_user,
  password: sport4all,
  queueId: events,
}

s3: {
  bucket: sport4all,
  region: us-east-2,
}
