server: {
  ip: localhost,
  port: 8080,
}

api: {
  baseUrl: /api,
  settingsURL: /settings,
}

logger: {
  logfile: stdout,
  level: debug,
}

database: {
  dbms: postgres,
  host: localhost,
  user: sport4all_user,
  password: sport4all,
  name: sport4all_db,
  sslmode: disable
}

