logger: {
  logfile: stdout,
  level: debug,
}

api: {
  baseUrl: /api,
  settingsURL: /settings,
  profileURL: /profile,
  sessionsUrl: /sessions
}

server: {
  address: localhost:8080,
}

origins: {
  allowed_origins: [
      http://localhost:8080
  ]
}

psql: {
  dbms: postgres,
  host: localhost,
  user: sport4all_user,
  password: sport4all,
  name: sport4all_db,
  sslmode: disable
}

redis: {
  address: localhost:6379,
  protocol: tcp,
  expiresKeySec: 120,
}
